# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/docs'

# Dates are not included in permalinks
permalink: none

collections:
  guides:
    title: "BigPanda University"
  integrations:
    title: "Integrations"
  faqs:
    title: "FAQs"

future: true

# Exclude non-site files
exclude: ['lib', 'README.md', "package.json", "node_modules", "bower.json", "public_prod", "public", "*.sh", "dev.js"]

markdown: KramdownPygments
highlighter: pygments
kramdown:
  input: GFM

destination: 'public'
ga_code: false
production: false
kiss_metrics: false
