# Site title and subtitle. This is used in _includes/header.html
title: 'BigPanda'
subtitle: 'Documentation'
    #
codeurl: 'https://github.com/bigpandaio/docs.bigpanda.io'

collections:
  guides:
    title: "BigPanda University"
  integrations:
    title: "Integrations"
  faqs:
    title: "FAQs"


# Dates are not included in permalinks
permalink: none

highlighter: pygments

future: true

# Exclude non-site files
exclude: ['lib', 'README.md', "package.json", "node_modules", "bower.json", "public_prod", "public", 'stylus', "*.sh", "dev.js", 'base.js', 'prod.js']


markdown: KramdownPygments
highlighter: pygments
kramdown:
  input: GFM

destination: 'public_prod'
production: true
ga_code: 'UA-40027187-7'
kiss_metrics: '84ab77b86fc690e90c1b37db36da3f1946a97c90'
